sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t caption01/muti-docker-testing -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true caption01/muti-docker-testing npm run test -- --coverage

after_success:
  - docker build -t caption01/muti-docker-client ./client
  - docker build -t caption01/muti-docker-nginx ./nginx
  - docker build -t caption01/muti-docker-server ./server
  - docker build -t caption01/muti-docker-worker ./worker
  # LOGIN TO DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # PUSH IMAGES TO DOCKER HUB
  - docker push caption01/muti-docker-client
  - docker push caption01/muti-docker-nginx
  - docker push caption01/muti-docker-server
  - docker push caption01/muti-docker-worker

deploy:
  # edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "muti-docker-2"
  env: "MutiDocker2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-616520069289"
  bucket_path: "docker-muti-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
